# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDockWidget, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QPushButton, QSizePolicy, QSpacerItem, QStatusBar,
    QTabWidget, QToolButton, QVBoxLayout, QWidget)

from ui.joystick_widget import Joystick
from ui.scaled_label import ScaledLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1035, 798)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamilies([u"Meiryo UI"])
        MainWindow.setFont(font)
        MainWindow.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QMainWindow.AllowNestedDocks|QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.actionL_Stick_Control = QAction(MainWindow)
        self.actionL_Stick_Control.setObjectName(u"actionL_Stick_Control")
        self.actionL_Stick_Control.setCheckable(True)
        self.actionL_Stick_Control.setChecked(False)
        self.actionL_Stick_Control.setEnabled(False)
        self.actionL_Stick_Control.setFont(font)
        self.actionR_Stick_Control = QAction(MainWindow)
        self.actionR_Stick_Control.setObjectName(u"actionR_Stick_Control")
        self.actionR_Stick_Control.setCheckable(True)
        self.actionR_Stick_Control.setEnabled(False)
        self.actionR_Stick_Control.setFont(font)
        self.actionKeyboard_Control = QAction(MainWindow)
        self.actionKeyboard_Control.setObjectName(u"actionKeyboard_Control")
        self.actionKeyboard_Control.setCheckable(True)
        self.actionKeyboard_Control.setEnabled(False)
        self.actionKeyboard_Control.setFont(font)
        self.actionGuiControllerOpen = QAction(MainWindow)
        self.actionGuiControllerOpen.setObjectName(u"actionGuiControllerOpen")
        self.actionGuiControllerOpen.setFont(font)
        self.actionGuiSetting = QAction(MainWindow)
        self.actionGuiSetting.setObjectName(u"actionGuiSetting")
        self.actionGuiSetting.setEnabled(False)
        self.actionGuiSetting.setFont(font)
        self.actionSetting = QAction(MainWindow)
        self.actionSetting.setObjectName(u"actionSetting")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon = QIcon()
        iconThemeName = u"application-exit"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u"C:/Users/Moi/PycharmProjects/SWCon-Pyside/ui", QSize(), QIcon.Normal, QIcon.Off)
        
        self.actionQuit.setIcon(icon)
        self.actionShow_Serial = QAction(MainWindow)
        self.actionShow_Serial.setObjectName(u"actionShow_Serial")
        self.actionShow_Serial.setCheckable(True)
        self.actionShow_Camera_Realtime = QAction(MainWindow)
        self.actionShow_Camera_Realtime.setObjectName(u"actionShow_Camera_Realtime")
        self.actionShow_Camera_Realtime.setCheckable(True)
        self.actionShow_Camera_Realtime.setEnabled(False)
        self.actionLog_Window = QAction(MainWindow)
        self.actionLog_Window.setObjectName(u"actionLog_Window")
        self.actionconnect = QAction(MainWindow)
        self.actionconnect.setObjectName(u"actionconnect")
        self.actionsetting = QAction(MainWindow)
        self.actionsetting.setObjectName(u"actionsetting")
        self.actionsetting.setEnabled(False)
        self.actionCOM_Port_ASSIST = QAction(MainWindow)
        self.actionCOM_Port_ASSIST.setObjectName(u"actionCOM_Port_ASSIST")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(False)
        self.gridLayout_7 = QGridLayout(self.centralwidget)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.CaptureImageArea = ScaledLabel(self.centralwidget)
        self.CaptureImageArea.setObjectName(u"CaptureImageArea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.CaptureImageArea.sizePolicy().hasHeightForWidth())
        self.CaptureImageArea.setSizePolicy(sizePolicy1)
        self.CaptureImageArea.setMinimumSize(QSize(640, 360))
        self.CaptureImageArea.setMaximumSize(QSize(1920, 1080))
        self.CaptureImageArea.setSizeIncrement(QSize(0, 0))
        self.CaptureImageArea.setCursor(QCursor(Qt.CrossCursor))
        self.CaptureImageArea.setLayoutDirection(Qt.LeftToRight)
        self.CaptureImageArea.setAutoFillBackground(False)
        self.CaptureImageArea.setStyleSheet(u"background-color:rgb(138, 230, 255)")
        self.CaptureImageArea.setFrameShape(QFrame.StyledPanel)
        self.CaptureImageArea.setFrameShadow(QFrame.Sunken)
        self.CaptureImageArea.setLineWidth(1)
        self.CaptureImageArea.setScaledContents(True)
        self.CaptureImageArea.setAlignment(Qt.AlignCenter)
        self.CaptureImageArea.setMargin(0)

        self.gridLayout_4.addWidget(self.CaptureImageArea, 2, 0, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Plain)
        self.gridLayout_2 = QGridLayout(self.frame)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.frame)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMaximumSize(QSize(16777215, 121))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabPosition(QTabWidget.West)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tab.setAutoFillBackground(True)
        self.gridLayout_5 = QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.toolButtonOpenPythonDir = QToolButton(self.tab)
        self.toolButtonOpenPythonDir.setObjectName(u"toolButtonOpenPythonDir")

        self.gridLayout_5.addWidget(self.toolButtonOpenPythonDir, 0, 5, 1, 1)

        self.horizontalSpacer = QSpacerItem(419, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_5.addItem(self.horizontalSpacer, 1, 0, 1, 1)

        self.pushButton_PythonReload = QPushButton(self.tab)
        self.pushButton_PythonReload.setObjectName(u"pushButton_PythonReload")
        self.pushButton_PythonReload.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_PythonReload.sizePolicy().hasHeightForWidth())
        self.pushButton_PythonReload.setSizePolicy(sizePolicy2)
        self.pushButton_PythonReload.setMinimumSize(QSize(80, 0))

        self.gridLayout_5.addWidget(self.pushButton_PythonReload, 1, 1, 1, 1)

        self.comboBoxPython = QComboBox(self.tab)
        self.comboBoxPython.setObjectName(u"comboBoxPython")

        self.gridLayout_5.addWidget(self.comboBoxPython, 0, 0, 1, 5)

        self.pushButton_PythonStop = QPushButton(self.tab)
        self.pushButton_PythonStop.setObjectName(u"pushButton_PythonStop")
        sizePolicy2.setHeightForWidth(self.pushButton_PythonStop.sizePolicy().hasHeightForWidth())
        self.pushButton_PythonStop.setSizePolicy(sizePolicy2)
        self.pushButton_PythonStop.setMinimumSize(QSize(80, 0))

        self.gridLayout_5.addWidget(self.pushButton_PythonStop, 1, 4, 1, 2)

        self.pushButton_PythonStart = QPushButton(self.tab)
        self.pushButton_PythonStart.setObjectName(u"pushButton_PythonStart")
        self.pushButton_PythonStart.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.pushButton_PythonStart.sizePolicy().hasHeightForWidth())
        self.pushButton_PythonStart.setSizePolicy(sizePolicy2)
        self.pushButton_PythonStart.setMinimumSize(QSize(80, 0))

        self.gridLayout_5.addWidget(self.pushButton_PythonStart, 1, 2, 1, 2)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setAutoFillBackground(True)
        self.gridLayout_6 = QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.pushButton_MCUStart = QPushButton(self.tab_2)
        self.pushButton_MCUStart.setObjectName(u"pushButton_MCUStart")
        sizePolicy2.setHeightForWidth(self.pushButton_MCUStart.sizePolicy().hasHeightForWidth())
        self.pushButton_MCUStart.setSizePolicy(sizePolicy2)
        self.pushButton_MCUStart.setMinimumSize(QSize(80, 0))

        self.gridLayout_6.addWidget(self.pushButton_MCUStart, 1, 2, 1, 1)

        self.toolButton_OpenMCUDir = QToolButton(self.tab_2)
        self.toolButton_OpenMCUDir.setObjectName(u"toolButton_OpenMCUDir")

        self.gridLayout_6.addWidget(self.toolButton_OpenMCUDir, 0, 4, 1, 1)

        self.comboBox_MCU = QComboBox(self.tab_2)
        self.comboBox_MCU.setObjectName(u"comboBox_MCU")

        self.gridLayout_6.addWidget(self.comboBox_MCU, 0, 0, 1, 4)

        self.horizontalSpacer_2 = QSpacerItem(419, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_6.addItem(self.horizontalSpacer_2, 1, 0, 1, 1)

        self.pushButton_MCUStop = QPushButton(self.tab_2)
        self.pushButton_MCUStop.setObjectName(u"pushButton_MCUStop")
        sizePolicy2.setHeightForWidth(self.pushButton_MCUStop.sizePolicy().hasHeightForWidth())
        self.pushButton_MCUStop.setSizePolicy(sizePolicy2)
        self.pushButton_MCUStop.setMinimumSize(QSize(80, 0))

        self.gridLayout_6.addWidget(self.pushButton_MCUStop, 1, 3, 1, 2)

        self.pushButton_MCUReload = QPushButton(self.tab_2)
        self.pushButton_MCUReload.setObjectName(u"pushButton_MCUReload")
        sizePolicy2.setHeightForWidth(self.pushButton_MCUReload.sizePolicy().hasHeightForWidth())
        self.pushButton_MCUReload.setSizePolicy(sizePolicy2)
        self.pushButton_MCUReload.setMinimumSize(QSize(80, 0))

        self.gridLayout_6.addWidget(self.pushButton_MCUReload, 1, 1, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")

        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)


        self.gridLayout_4.addWidget(self.frame, 3, 0, 1, 1)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy3)
        self.frame_2.setMaximumSize(QSize(16777215, 70))
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Plain)
        self.gridLayout_3 = QGridLayout(self.frame_2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 2)
        self.lineEditComPort = QLineEdit(self.frame_2)
        self.lineEditComPort.setObjectName(u"lineEditComPort")
        self.lineEditComPort.setMaximumSize(QSize(75, 16777215))
        self.lineEditComPort.setFocusPolicy(Qt.StrongFocus)
        self.lineEditComPort.setAlignment(Qt.AlignCenter)
        self.lineEditComPort.setClearButtonEnabled(False)

        self.gridLayout_3.addWidget(self.lineEditComPort, 0, 4, 1, 1)

        self.pushButtonReloadCamera = QPushButton(self.frame_2)
        self.pushButtonReloadCamera.setObjectName(u"pushButtonReloadCamera")

        self.gridLayout_3.addWidget(self.pushButtonReloadCamera, 1, 5, 1, 1)

        self.line = QFrame(self.frame_2)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.gridLayout_3.addWidget(self.line, 0, 6, 2, 1)

        self.pushButtonScreenShot = QPushButton(self.frame_2)
        self.pushButtonScreenShot.setObjectName(u"pushButtonScreenShot")
        self.pushButtonScreenShot.setCheckable(False)
        self.pushButtonScreenShot.setFlat(False)

        self.gridLayout_3.addWidget(self.pushButtonScreenShot, 0, 7, 1, 1)

        self.pushButtonClearLog = QPushButton(self.frame_2)
        self.pushButtonClearLog.setObjectName(u"pushButtonClearLog")

        self.gridLayout_3.addWidget(self.pushButtonClearLog, 1, 7, 1, 2)

        self.toolButtonOpenScreenShotDir = QToolButton(self.frame_2)
        self.toolButtonOpenScreenShotDir.setObjectName(u"toolButtonOpenScreenShotDir")

        self.gridLayout_3.addWidget(self.toolButtonOpenScreenShotDir, 0, 8, 1, 1)

        self.pushButtonReloadPort = QPushButton(self.frame_2)
        self.pushButtonReloadPort.setObjectName(u"pushButtonReloadPort")
        self.pushButtonReloadPort.setAutoFillBackground(False)
        self.pushButtonReloadPort.setFlat(False)

        self.gridLayout_3.addWidget(self.pushButtonReloadPort, 0, 5, 1, 1)

        self.lineEditCameraID = QLineEdit(self.frame_2)
        self.lineEditCameraID.setObjectName(u"lineEditCameraID")
        self.lineEditCameraID.setMaximumSize(QSize(100, 16777215))
        self.lineEditCameraID.setFocusPolicy(Qt.StrongFocus)
        self.lineEditCameraID.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.lineEditCameraID, 0, 3, 1, 1)

        self.lineEditFPS = QLineEdit(self.frame_2)
        self.lineEditFPS.setObjectName(u"lineEditFPS")
        self.lineEditFPS.setMaximumSize(QSize(80, 16777215))
        self.lineEditFPS.setFocusPolicy(Qt.StrongFocus)
        self.lineEditFPS.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.lineEditFPS, 0, 2, 1, 1)

        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)

        self.comboBoxCameraNames = QComboBox(self.frame_2)
        self.comboBoxCameraNames.setObjectName(u"comboBoxCameraNames")
        self.comboBoxCameraNames.setEnabled(True)
        self.comboBoxCameraNames.setToolTipDuration(1)
        self.comboBoxCameraNames.setEditable(False)
        self.comboBoxCameraNames.setMaxVisibleItems(10)

        self.gridLayout_3.addWidget(self.comboBoxCameraNames, 1, 1, 1, 4)


        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)


        self.gridLayout_7.addLayout(self.gridLayout_4, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1035, 22))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        self.menuOption = QMenu(self.menubar)
        self.menuOption.setObjectName(u"menuOption")
        sizePolicy3.setHeightForWidth(self.menuOption.sizePolicy().hasHeightForWidth())
        self.menuOption.setSizePolicy(sizePolicy3)
        self.menuGUI_Controller = QMenu(self.menubar)
        self.menuGUI_Controller.setObjectName(u"menuGUI_Controller")
        self.menuGUI_Controller_2 = QMenu(self.menuGUI_Controller)
        self.menuGUI_Controller_2.setObjectName(u"menuGUI_Controller_2")
        self.menuGamepad_Controller = QMenu(self.menuGUI_Controller)
        self.menuGamepad_Controller.setObjectName(u"menuGamepad_Controller")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_log = QDockWidget(MainWindow)
        self.dockWidget_log.setObjectName(u"dockWidget_log")
        self.dockWidget_log.setEnabled(True)
        sizePolicy.setHeightForWidth(self.dockWidget_log.sizePolicy().hasHeightForWidth())
        self.dockWidget_log.setSizePolicy(sizePolicy)
        self.dockWidget_log.setMaximumSize(QSize(524287, 524287))
        self.dockWidget_log.setContextMenuPolicy(Qt.NoContextMenu)
        self.dockWidget_log.setAutoFillBackground(True)
        self.dockWidget_log.setFeatures(QDockWidget.DockWidgetClosable|QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidget_log.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy4)
        self.gridLayout = QGridLayout(self.dockWidgetContents)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.plainTextEdit = QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setUndoRedoEnabled(True)
        self.plainTextEdit.setCursorWidth(-2)
        self.plainTextEdit.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.plainTextEdit.setBackgroundVisible(False)

        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)

        self.dockWidget_log.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.BottomDockWidgetArea, self.dockWidget_log)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_left = QDockWidget(MainWindow)
        self.dockWidget_left.setObjectName(u"dockWidget_left")
        self.dockWidget_left.setFeatures(QDockWidget.DockWidgetClosable|QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.horizontalLayout_2 = QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.joycon_l = QFrame(self.dockWidgetContents_2)
        self.joycon_l.setObjectName(u"joycon_l")
        self.joycon_l.setMinimumSize(QSize(150, 0))
        self.joycon_l.setMaximumSize(QSize(150, 16777215))
        self.joycon_l.setFrameShape(QFrame.StyledPanel)
        self.joycon_l.setFrameShadow(QFrame.Raised)
        self.gridLayout_18 = QGridLayout(self.joycon_l)
        self.gridLayout_18.setObjectName(u"gridLayout_18")
        self.frame_15 = QFrame(self.joycon_l)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.frame_15)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalSpacer_5 = QSpacerItem(0, 35, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_5.addItem(self.verticalSpacer_5)

        self.BTN_zl = QPushButton(self.frame_15)
        self.BTN_zl.setObjectName(u"BTN_zl")
        self.BTN_zl.setMinimumSize(QSize(120, 30))
        self.BTN_zl.setMaximumSize(QSize(160, 30))
        font1 = QFont()
        font1.setFamilies([u"Meiryo UI"])
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        self.BTN_zl.setFont(font1)
        self.BTN_zl.setAutoFillBackground(False)
        self.BTN_zl.setIconSize(QSize(108, 48))
        self.BTN_zl.setCheckable(True)
        self.BTN_zl.setFlat(True)

        self.verticalLayout_5.addWidget(self.BTN_zl, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.BTN_l = QPushButton(self.frame_15)
        self.BTN_l.setObjectName(u"BTN_l")
        self.BTN_l.setMinimumSize(QSize(120, 30))
        self.BTN_l.setMaximumSize(QSize(120, 30))
        self.BTN_l.setFont(font1)
        self.BTN_l.setAutoFillBackground(False)
        self.BTN_l.setIconSize(QSize(32, 32))
        self.BTN_l.setCheckable(True)
        self.BTN_l.setFlat(False)

        self.verticalLayout_5.addWidget(self.BTN_l, 0, Qt.AlignHCenter)

        self.frame_16 = QFrame(self.frame_15)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setMinimumSize(QSize(0, 30))
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.gridLayout_19 = QGridLayout(self.frame_16)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName(u"gridLayout_19")
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_19.addItem(self.horizontalSpacer_7, 1, 1, 1, 1)

        self.BTN_minus = QPushButton(self.frame_16)
        self.BTN_minus.setObjectName(u"BTN_minus")
        self.BTN_minus.setMinimumSize(QSize(30, 30))
        self.BTN_minus.setMaximumSize(QSize(30, 30))
        font2 = QFont()
        font2.setFamilies([u"Yu Gothic UI"])
        font2.setPointSize(16)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        self.BTN_minus.setFont(font2)
        self.BTN_minus.setAutoFillBackground(False)
        self.BTN_minus.setIconSize(QSize(32, 32))
        self.BTN_minus.setCheckable(True)
        self.BTN_minus.setFlat(True)

        self.gridLayout_19.addWidget(self.BTN_minus, 1, 3, 1, 1)

        self.BTN_ls = QPushButton(self.frame_16)
        self.BTN_ls.setObjectName(u"BTN_ls")
        self.BTN_ls.setMinimumSize(QSize(30, 30))
        self.BTN_ls.setMaximumSize(QSize(30, 30))
        self.BTN_ls.setFont(font1)
        self.BTN_ls.setAutoFillBackground(False)
        self.BTN_ls.setIconSize(QSize(32, 32))
        self.BTN_ls.setCheckable(True)
        self.BTN_ls.setFlat(True)

        self.gridLayout_19.addWidget(self.BTN_ls, 1, 0, 1, 1)


        self.verticalLayout_5.addWidget(self.frame_16)

        self.frame_17 = QFrame(self.frame_15)
        self.frame_17.setObjectName(u"frame_17")
        sizePolicy5 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy5)
        self.frame_17.setMinimumSize(QSize(120, 120))
        self.frame_17.setMaximumSize(QSize(120, 120))
        self.frame_17.setFrameShadow(QFrame.Raised)
        self.gridLayout_20 = QGridLayout(self.frame_17)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName(u"gridLayout_20")
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.left_stick = Joystick(self.frame_17)
        self.left_stick.setObjectName(u"left_stick")
        sizePolicy5.setHeightForWidth(self.left_stick.sizePolicy().hasHeightForWidth())
        self.left_stick.setSizePolicy(sizePolicy5)
        self.left_stick.setMinimumSize(QSize(120, 120))
        self.left_stick.setMaximumSize(QSize(120, 120))
        self.verticalLayout_6 = QVBoxLayout(self.left_stick)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_20.addWidget(self.left_stick, 0, 0, 1, 1)


        self.verticalLayout_5.addWidget(self.frame_17, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frame_19 = QFrame(self.frame_15)
        self.frame_19.setObjectName(u"frame_19")
        sizePolicy5.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy5)
        self.frame_19.setMinimumSize(QSize(120, 120))
        self.frame_19.setMaximumSize(QSize(120, 120))
        self.frame_19.setFrameShadow(QFrame.Sunken)
        self.gridLayout_21 = QGridLayout(self.frame_19)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName(u"gridLayout_21")
        self.BTN_up = QPushButton(self.frame_19)
        self.BTN_up.setObjectName(u"BTN_up")
        self.BTN_up.setMinimumSize(QSize(30, 30))
        self.BTN_up.setMaximumSize(QSize(30, 30))
        self.BTN_up.setCheckable(True)

        self.gridLayout_21.addWidget(self.BTN_up, 0, 1, 1, 1)

        self.BTN_right = QPushButton(self.frame_19)
        self.BTN_right.setObjectName(u"BTN_right")
        self.BTN_right.setMinimumSize(QSize(30, 30))
        self.BTN_right.setMaximumSize(QSize(30, 30))
        self.BTN_right.setCheckable(True)

        self.gridLayout_21.addWidget(self.BTN_right, 1, 2, 1, 1)

        self.BTN_left = QPushButton(self.frame_19)
        self.BTN_left.setObjectName(u"BTN_left")
        self.BTN_left.setMinimumSize(QSize(30, 30))
        self.BTN_left.setMaximumSize(QSize(30, 30))
        self.BTN_left.setCheckable(True)

        self.gridLayout_21.addWidget(self.BTN_left, 1, 0, 1, 1)

        self.BTN_down = QPushButton(self.frame_19)
        self.BTN_down.setObjectName(u"BTN_down")
        self.BTN_down.setMinimumSize(QSize(30, 30))
        self.BTN_down.setMaximumSize(QSize(30, 30))
        self.BTN_down.setCheckable(True)
        self.BTN_down.setFlat(False)

        self.gridLayout_21.addWidget(self.BTN_down, 2, 1, 1, 1)


        self.verticalLayout_5.addWidget(self.frame_19, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frame_20 = QFrame(self.frame_15)
        self.frame_20.setObjectName(u"frame_20")
        self.frame_20.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_20)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_8 = QSpacerItem(97, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_8)

        self.BTN_capture = QPushButton(self.frame_20)
        self.BTN_capture.setObjectName(u"BTN_capture")
        self.BTN_capture.setMinimumSize(QSize(32, 32))
        self.BTN_capture.setMaximumSize(QSize(32, 32))
        icon1 = QIcon()
        icon1.addFile(u"assets/Capture.png", QSize(), QIcon.Normal, QIcon.Off)
        self.BTN_capture.setIcon(icon1)
        self.BTN_capture.setIconSize(QSize(32, 32))
        self.BTN_capture.setCheckable(True)
        self.BTN_capture.setFlat(True)

        self.horizontalLayout_4.addWidget(self.BTN_capture)


        self.verticalLayout_5.addWidget(self.frame_20)


        self.gridLayout_18.addWidget(self.frame_15, 0, 0, 1, 1)

        self.verticalSpacer_6 = QSpacerItem(20, 30, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout_18.addItem(self.verticalSpacer_6, 1, 0, 1, 1)


        self.horizontalLayout_2.addWidget(self.joycon_l)

        self.dockWidget_left.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.dockWidget_left)
        self.dockWidget_right = QDockWidget(MainWindow)
        self.dockWidget_right.setObjectName(u"dockWidget_right")
        self.dockWidgetContents_8 = QWidget()
        self.dockWidgetContents_8.setObjectName(u"dockWidgetContents_8")
        self.dockWidgetContents_8.setMaximumSize(QSize(150, 16777215))
        self.horizontalLayout = QHBoxLayout(self.dockWidgetContents_8)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.joycon_r = QFrame(self.dockWidgetContents_8)
        self.joycon_r.setObjectName(u"joycon_r")
        self.joycon_r.setMinimumSize(QSize(150, 0))
        self.joycon_r.setMaximumSize(QSize(150, 16777215))
        self.joycon_r.setFrameShape(QFrame.StyledPanel)
        self.joycon_r.setFrameShadow(QFrame.Raised)
        self.gridLayout_23 = QGridLayout(self.joycon_r)
        self.gridLayout_23.setObjectName(u"gridLayout_23")
        self.frame_21 = QFrame(self.joycon_r)
        self.frame_21.setObjectName(u"frame_21")
        self.frame_21.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.frame_21)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalSpacer_7 = QSpacerItem(0, 35, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.verticalLayout_7.addItem(self.verticalSpacer_7)

        self.BTN_zr = QPushButton(self.frame_21)
        self.BTN_zr.setObjectName(u"BTN_zr")
        self.BTN_zr.setMinimumSize(QSize(120, 30))
        self.BTN_zr.setMaximumSize(QSize(160, 30))
        self.BTN_zr.setFont(font1)
        self.BTN_zr.setAutoFillBackground(False)
        self.BTN_zr.setIconSize(QSize(108, 48))
        self.BTN_zr.setCheckable(True)
        self.BTN_zr.setFlat(True)

        self.verticalLayout_7.addWidget(self.BTN_zr, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.BTN_r = QPushButton(self.frame_21)
        self.BTN_r.setObjectName(u"BTN_r")
        self.BTN_r.setMinimumSize(QSize(120, 30))
        self.BTN_r.setMaximumSize(QSize(120, 30))
        self.BTN_r.setFont(font1)
        self.BTN_r.setAutoFillBackground(False)
        self.BTN_r.setIconSize(QSize(32, 32))
        self.BTN_r.setCheckable(True)
        self.BTN_r.setFlat(False)

        self.verticalLayout_7.addWidget(self.BTN_r, 0, Qt.AlignHCenter)

        self.frame_22 = QFrame(self.frame_21)
        self.frame_22.setObjectName(u"frame_22")
        self.frame_22.setMinimumSize(QSize(0, 30))
        self.frame_22.setFrameShadow(QFrame.Raised)
        self.gridLayout_24 = QGridLayout(self.frame_22)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName(u"gridLayout_24")
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_9 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_24.addItem(self.horizontalSpacer_9, 1, 2, 1, 1)

        self.BTN_plus = QPushButton(self.frame_22)
        self.BTN_plus.setObjectName(u"BTN_plus")
        self.BTN_plus.setMinimumSize(QSize(30, 30))
        self.BTN_plus.setMaximumSize(QSize(30, 30))
        self.BTN_plus.setFont(font2)
        self.BTN_plus.setAutoFillBackground(False)
        self.BTN_plus.setIconSize(QSize(32, 32))
        self.BTN_plus.setCheckable(True)
        self.BTN_plus.setFlat(True)

        self.gridLayout_24.addWidget(self.BTN_plus, 1, 0, 1, 1)

        self.BTN_rs = QPushButton(self.frame_22)
        self.BTN_rs.setObjectName(u"BTN_rs")
        self.BTN_rs.setMinimumSize(QSize(30, 30))
        self.BTN_rs.setMaximumSize(QSize(30, 30))
        self.BTN_rs.setFont(font1)
        self.BTN_rs.setAutoFillBackground(False)
        self.BTN_rs.setIconSize(QSize(32, 32))
        self.BTN_rs.setCheckable(True)
        self.BTN_rs.setFlat(True)

        self.gridLayout_24.addWidget(self.BTN_rs, 1, 3, 1, 1)


        self.verticalLayout_7.addWidget(self.frame_22)

        self.frame_23 = QFrame(self.frame_21)
        self.frame_23.setObjectName(u"frame_23")
        sizePolicy5.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy5)
        self.frame_23.setMinimumSize(QSize(120, 120))
        self.frame_23.setMaximumSize(QSize(120, 120))
        self.gridLayout_25 = QGridLayout(self.frame_23)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName(u"gridLayout_25")
        self.BTN_x = QPushButton(self.frame_23)
        self.BTN_x.setObjectName(u"BTN_x")
        self.BTN_x.setMinimumSize(QSize(30, 30))
        self.BTN_x.setMaximumSize(QSize(30, 30))
        font3 = QFont()
        font3.setFamilies([u"Meiryo UI"])
        font3.setPointSize(12)
        self.BTN_x.setFont(font3)
        self.BTN_x.setCheckable(True)

        self.gridLayout_25.addWidget(self.BTN_x, 0, 1, 1, 1)

        self.BTN_a = QPushButton(self.frame_23)
        self.BTN_a.setObjectName(u"BTN_a")
        self.BTN_a.setMinimumSize(QSize(30, 30))
        self.BTN_a.setMaximumSize(QSize(30, 30))
        self.BTN_a.setFont(font3)
        self.BTN_a.setCheckable(True)

        self.gridLayout_25.addWidget(self.BTN_a, 1, 2, 1, 1)

        self.BTN_y = QPushButton(self.frame_23)
        self.BTN_y.setObjectName(u"BTN_y")
        self.BTN_y.setMinimumSize(QSize(30, 30))
        self.BTN_y.setMaximumSize(QSize(30, 30))
        self.BTN_y.setFont(font3)
        self.BTN_y.setCheckable(True)

        self.gridLayout_25.addWidget(self.BTN_y, 1, 0, 1, 1)

        self.BTN_b = QPushButton(self.frame_23)
        self.BTN_b.setObjectName(u"BTN_b")
        self.BTN_b.setMinimumSize(QSize(30, 30))
        self.BTN_b.setMaximumSize(QSize(30, 30))
        self.BTN_b.setFont(font3)
        self.BTN_b.setCheckable(True)
        self.BTN_b.setFlat(False)

        self.gridLayout_25.addWidget(self.BTN_b, 2, 1, 1, 1)


        self.verticalLayout_7.addWidget(self.frame_23, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frame_24 = QFrame(self.frame_21)
        self.frame_24.setObjectName(u"frame_24")
        sizePolicy5.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy5)
        self.frame_24.setMinimumSize(QSize(120, 120))
        self.frame_24.setMaximumSize(QSize(120, 120))
        self.frame_24.setFrameShadow(QFrame.Raised)
        self.gridLayout_26 = QGridLayout(self.frame_24)
        self.gridLayout_26.setSpacing(0)
        self.gridLayout_26.setObjectName(u"gridLayout_26")
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.right_stick = Joystick(self.frame_24)
        self.right_stick.setObjectName(u"right_stick")
        sizePolicy5.setHeightForWidth(self.right_stick.sizePolicy().hasHeightForWidth())
        self.right_stick.setSizePolicy(sizePolicy5)
        self.right_stick.setMinimumSize(QSize(120, 120))
        self.right_stick.setMaximumSize(QSize(120, 120))
        self.verticalLayout_8 = QVBoxLayout(self.right_stick)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_26.addWidget(self.right_stick, 0, 0, 1, 1)


        self.verticalLayout_7.addWidget(self.frame_24, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.frame_26 = QFrame(self.frame_21)
        self.frame_26.setObjectName(u"frame_26")
        self.frame_26.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.frame_26)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.BTN_home = QPushButton(self.frame_26)
        self.BTN_home.setObjectName(u"BTN_home")
        self.BTN_home.setMinimumSize(QSize(32, 32))
        self.BTN_home.setMaximumSize(QSize(32, 32))
        icon2 = QIcon()
        icon2.addFile(u"assets/Home.png", QSize(), QIcon.Normal, QIcon.Off)
        self.BTN_home.setIcon(icon2)
        self.BTN_home.setIconSize(QSize(32, 32))
        self.BTN_home.setCheckable(True)
        self.BTN_home.setFlat(True)

        self.horizontalLayout_5.addWidget(self.BTN_home)

        self.horizontalSpacer_10 = QSpacerItem(97, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_10)


        self.verticalLayout_7.addWidget(self.frame_26)


        self.gridLayout_23.addWidget(self.frame_21, 0, 0, 1, 1)

        self.verticalSpacer_8 = QSpacerItem(20, 30, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout_23.addItem(self.verticalSpacer_8, 1, 0, 1, 1)


        self.horizontalLayout.addWidget(self.joycon_r)

        self.dockWidget_right.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.dockWidget_right)
        QWidget.setTabOrder(self.tabWidget, self.plainTextEdit)
        QWidget.setTabOrder(self.plainTextEdit, self.lineEditFPS)
        QWidget.setTabOrder(self.lineEditFPS, self.lineEditCameraID)
        QWidget.setTabOrder(self.lineEditCameraID, self.lineEditComPort)
        QWidget.setTabOrder(self.lineEditComPort, self.pushButtonReloadPort)
        QWidget.setTabOrder(self.pushButtonReloadPort, self.pushButtonScreenShot)
        QWidget.setTabOrder(self.pushButtonScreenShot, self.toolButtonOpenScreenShotDir)
        QWidget.setTabOrder(self.toolButtonOpenScreenShotDir, self.comboBoxCameraNames)
        QWidget.setTabOrder(self.comboBoxCameraNames, self.pushButtonReloadCamera)
        QWidget.setTabOrder(self.pushButtonReloadCamera, self.pushButtonClearLog)
        QWidget.setTabOrder(self.pushButtonClearLog, self.comboBoxPython)
        QWidget.setTabOrder(self.comboBoxPython, self.toolButtonOpenPythonDir)
        QWidget.setTabOrder(self.toolButtonOpenPythonDir, self.pushButton_PythonStart)
        QWidget.setTabOrder(self.pushButton_PythonStart, self.pushButton_PythonStop)
        QWidget.setTabOrder(self.pushButton_PythonStop, self.comboBox_MCU)
        QWidget.setTabOrder(self.comboBox_MCU, self.toolButton_OpenMCUDir)
        QWidget.setTabOrder(self.toolButton_OpenMCUDir, self.pushButton_MCUStart)
        QWidget.setTabOrder(self.pushButton_MCUStart, self.pushButton_MCUStop)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuGUI_Controller.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menuMenu.addAction(self.actionSetting)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionQuit)
        self.menuOption.addAction(self.actionShow_Camera_Realtime)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionShow_Serial)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionKeyboard_Control)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionCOM_Port_ASSIST)
        self.menuGUI_Controller.addAction(self.menuGUI_Controller_2.menuAction())
        self.menuGUI_Controller.addAction(self.menuGamepad_Controller.menuAction())
        self.menuGUI_Controller_2.addAction(self.actionGuiControllerOpen)
        self.menuGUI_Controller_2.addAction(self.actionGuiSetting)
        self.menuGamepad_Controller.addAction(self.actionconnect)
        self.menuGamepad_Controller.addAction(self.actionsetting)
        self.menuWindow.addAction(self.actionLog_Window)

        self.retranslateUi(MainWindow)
        self.actionLog_Window.triggered.connect(self.dockWidget_log.showNormal)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionGuiControllerOpen.triggered.connect(self.dockWidget_left.showNormal)
        self.actionGuiControllerOpen.triggered.connect(self.dockWidget_right.showNormal)
        self.actionShow_Serial.triggered["bool"].connect(MainWindow.show_serial)

        self.tabWidget.setCurrentIndex(0)
        self.pushButton_PythonReload.setDefault(False)
        self.pushButton_PythonStart.setDefault(True)
        self.pushButton_MCUStart.setDefault(True)
        self.pushButtonScreenShot.setDefault(False)
        self.comboBoxCameraNames.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionL_Stick_Control.setText(QCoreApplication.translate("MainWindow", u"L Stick Control", None))
        self.actionR_Stick_Control.setText(QCoreApplication.translate("MainWindow", u"R Stick Control", None))
        self.actionKeyboard_Control.setText(QCoreApplication.translate("MainWindow", u"Keyboard Control(\u5b9f\u88c5\u672a\u5b9a)", None))
        self.actionGuiControllerOpen.setText(QCoreApplication.translate("MainWindow", u"\u8868\u793a", None))
        self.actionGuiSetting.setText(QCoreApplication.translate("MainWindow", u"\u8a2d\u5b9a(\u5b9f\u88c5\u672a\u5b9a)", None))
        self.actionSetting.setText(QCoreApplication.translate("MainWindow", u"Setting", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionShow_Serial.setText(QCoreApplication.translate("MainWindow", u"Show Serial", None))
        self.actionShow_Camera_Realtime.setText(QCoreApplication.translate("MainWindow", u"Show Camera Realtime", None))
        self.actionLog_Window.setText(QCoreApplication.translate("MainWindow", u"Log Window", None))
        self.actionconnect.setText(QCoreApplication.translate("MainWindow", u"\u63a5\u7d9a", None))
        self.actionsetting.setText(QCoreApplication.translate("MainWindow", u"\u8a2d\u5b9a(\u5b9f\u88c5\u4e2d)", None))
        self.actionCOM_Port_ASSIST.setText(QCoreApplication.translate("MainWindow", u"\u5229\u7528\u53ef\u80fd\u306aCOM Port\u53d6\u5f97", None))
        self.CaptureImageArea.setText(QCoreApplication.translate("MainWindow", u"CaptureImage", None))
        self.toolButtonOpenPythonDir.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.pushButton_PythonReload.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.pushButton_PythonStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.pushButton_PythonStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Python", None))
        self.pushButton_MCUStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.toolButton_OpenMCUDir.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.pushButton_MCUStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.pushButton_MCUReload.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"MCU", None))
        self.lineEditComPort.setPlaceholderText(QCoreApplication.translate("MainWindow", u"COM Port", None))
        self.pushButtonReloadCamera.setText(QCoreApplication.translate("MainWindow", u"Reload Camera", None))
        self.pushButtonScreenShot.setText(QCoreApplication.translate("MainWindow", u"ScreenShot", None))
        self.pushButtonClearLog.setText(QCoreApplication.translate("MainWindow", u"Clear Log", None))
        self.toolButtonOpenScreenShotDir.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.pushButtonReloadPort.setText(QCoreApplication.translate("MainWindow", u"Reload Port", None))
        self.pushButtonReloadPort.setProperty("class", QCoreApplication.translate("MainWindow", u"h1_subtitle", None))
        self.lineEditCameraID.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Camera ID", None))
        self.lineEditFPS.setPlaceholderText(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Set: ", None))
#if QT_CONFIG(tooltip)
        self.comboBoxCameraNames.setToolTip(QCoreApplication.translate("MainWindow", u"Camera Name", None))
#endif // QT_CONFIG(tooltip)
        self.comboBoxCameraNames.setCurrentText("")
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.menuOption.setTitle(QCoreApplication.translate("MainWindow", u"Option", None))
        self.menuGUI_Controller.setTitle(QCoreApplication.translate("MainWindow", u"Controller", None))
        self.menuGUI_Controller_2.setTitle(QCoreApplication.translate("MainWindow", u"GUI Controller", None))
        self.menuGamepad_Controller.setTitle(QCoreApplication.translate("MainWindow", u"Gamepad Controller", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainWindow", u"Window", None))
        self.dockWidget_log.setWindowTitle(QCoreApplication.translate("MainWindow", u"Log", None))
        self.dockWidget_left.setWindowTitle(QCoreApplication.translate("MainWindow", u"Controller(LEFT)", None))
        self.BTN_zl.setText(QCoreApplication.translate("MainWindow", u"ZL", None))
        self.BTN_l.setText(QCoreApplication.translate("MainWindow", u"L", None))
        self.BTN_minus.setText(QCoreApplication.translate("MainWindow", u"\uff0d", None))
        self.BTN_ls.setText(QCoreApplication.translate("MainWindow", u"LS", None))
        self.BTN_up.setText(QCoreApplication.translate("MainWindow", u"\u25b2", None))
        self.BTN_right.setText(QCoreApplication.translate("MainWindow", u"\u25b6", None))
        self.BTN_left.setText(QCoreApplication.translate("MainWindow", u"\u25c0", None))
        self.BTN_down.setText(QCoreApplication.translate("MainWindow", u"\u25bc", None))
        self.dockWidget_right.setWindowTitle(QCoreApplication.translate("MainWindow", u"Controller(RIGHT)", None))
        self.BTN_zr.setText(QCoreApplication.translate("MainWindow", u"ZR", None))
        self.BTN_r.setText(QCoreApplication.translate("MainWindow", u"R", None))
        self.BTN_plus.setText(QCoreApplication.translate("MainWindow", u"\uff0b", None))
        self.BTN_rs.setText(QCoreApplication.translate("MainWindow", u"RS", None))
        self.BTN_x.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.BTN_a.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.BTN_y.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.BTN_b.setText(QCoreApplication.translate("MainWindow", u"B", None))
    # retranslateUi

